### ISSUE TITLE
[General] Deleting a user on API does not delete on Auth0

### ISSUE THREAD

**Issue by pchatard** [pchatard/giftlist#59]
Reproduction : 

Log in the front application, call the /users/me endpoint with DELETE method.
If the request succeeds, you're logged out of the application and deleted from our database.
Try logging in again via Auth0, it works and you'll have a lot of errors throughout the application.

How should we deal with this?

**Comment by ndureiss** [comment]
It should definitely delete user from our Auth0 user DB.

**Comment by ndureiss** [comment]
@pchatard it's on your's !

**Comment by pchatard** [comment]
Tested! Nice job @ndureiss.
Closing the issue.
