### ISSUE TITLE
[API] EDIT List : grantedUsersIds in PartialListDTO ?

### ISSUE THREAD

**Issue by pchatard** [pchatard/giftlist#60]
Endpoint : `/lists/listId`
Method : `PUT`

According to the Swagger, we can't pass an edited grantedUsers property in `PartialListDTO` ? 

I did not try it though. 

Is this an error in documentation or in the implementation?
Could you please clarify this point?

**Comment by ndureiss** [comment]
Have a look to [current deployed API version](https://giftlist-app-api.herokuapp.com/docs/#/List/Edit).

Editing a List expose a Partial<EditListDTO> :wink:

**Comment by ndureiss** [comment]
Fair. This endpoint shall make possible to add/remove granted users.

**Comment by pchatard** [comment]
Adding here that grantedUsers is missing in ListDTO (getLists, getList etc). If you can add it too, it would be nice 👍

**Comment by ndureiss** [comment]
grantedUsersIds will be added to ListDTO.

**Comment by ndureiss** [comment]
it's all yours @pchatard

**Comment by pchatard** [comment]
@ndureiss This one is complicated to test for me right now (without proper data and friends endpoints).

Plus, my problem is the PartialListDTO (for PUT) changed and is now waiting for ownersDTO and grantedUsersDTO arrays ?

For consistency with the list creation, could we keep ownersIds and grantedUsersIds instead ?

**Comment by ndureiss** [comment]
@pchatard think it's OK now 😄
