### ISSUE TITLE
[API] Share / Unshare List : Change behavior

### ISSUE THREAD

**Issue by pchatard** [pchatard/giftlist#61]
Endpoint : `/lists/listId/share` and `/lists/listId/unshare`
Method : `PUT`

As discussed earlier, I'd prefer keeping my granted users when I go private on a list.

Please find below the desired behavior:

Share : Updates `isShared` to true and creates a sharingCode if not already done.
Unshare : Updates `isShared` to false and **DOES NOT empty `grantedUsers`**.

When a user perform a GET /lists, the lists he is granted for should only be returned if isShared is true.

**Comment by ndureiss** [comment]
@pchatard fixed by #73.

**Comment by pchatard** [comment]
Thanks, will perform some tests on this before closing.

**Comment by pchatard** [comment]
Works perfectly, nice job @ndureiss !
