### ISSUE TITLE
[API] Create List : grantedUsers ids

### ISSUE THREAD

**Issue by pchatard** [pchatard/giftlist#62]
Endpoint : `/lists`
Method : `POST`

Currently, I have to pass an array of user ids to grantedUsersIds to create a list.
Problem is I will probably never access these ids because users endpoints don't return them?

Possible solutions:
- Accept a list of email addresses instead?
- Return the ids in the user endpoints?

This needs to be done for the PUT too.

**Comment by ndureiss** [comment]
Yes.
I thought about it already. I think we will manage a "giftlistUserName" to have unique name/id for each users.
I will use it in grantedUsersIds.

It allows to reveal neither auth0 ids nor user emails.

**Comment by pchatard** [comment]
Seems good to me !

**Comment by ndureiss** [comment]
Must be the case for OwnerIds too

**Comment by ndureiss** [comment]
partially fixed @pchatard. Propose to check IDs, closed if OK and reopen an issue for discussing how to retrieve users display names.

**Comment by pchatard** [comment]
Another one! Nice job mate!
