### ISSUE TITLE
[API] Get Gift(s) : isBooked

### ISSUE THREAD

**Issue by pchatard** [pchatard/giftlist#63]
Endpoint : `/lists/listId/gifts`
Method : `GET`

Currently, I can see the `isBooked` property even if it's a gift belonging to one of my lists.

Ideally, I should not be able to see the booking status if the gift belongs to a list I am the owner of. If it's not my list, then I should be able to see it.

**Comment by ndureiss** [comment]
@pchatard it's all yours

**Comment by pchatard** [comment]
Perfect, works like a charm! Closing related #66 too.
Thanks @ndureiss
