### ISSUE TITLE
[API] Edit Gift : Swagger error

### ISSUE THREAD

**Issue by pchatard** [pchatard/giftlist#65]
Endpoint : `/lists/listId/gifts/giftId`
Method : `PUT`

PartialGiftDTO should not include `listId`. 
Currently throws a 422 which is fine but the documentation is not right on this point.

**Comment by ndureiss** [comment]
Fixed by #72 . @pchatard for validation.

**Comment by pchatard** [comment]
Swagger nicely updated, closing!
