### ISSUE TITLE
[API] Create Gift : Remove inapropriate properties

### ISSUE THREAD

**Issue by pchatard** [pchatard/giftlist#68]
Endpoint : `/lists/listId/gifts`
Method : `POST`

The `CreateGiftDTO` contains the following mandatory properties : 
- `listId`
- `isBooked`

They both seems irrelevant or repetitive to me now. `listId` can be found in the query params and `isBooked` can be set to false by default now.

Could you do something about that please?

**Comment by ndureiss** [comment]
@pchatard the ball is in your court!

**Comment by pchatard** [comment]
Swagger verification ✅ 
I will perform some tests when implementing before closing the issue.

**Comment by pchatard** [comment]
Tested with success.
