### ISSUE TITLE
[API] Missing description field in List

### ISSUE THREAD

**Issue by pchatard** [pchatard/giftlist#74]
I planned a "description" field for my lists.
I think you forgot it on your models or maybe there is a reason for this?

If this is useless, I can simply delete it from the UI.

**Comment by ndureiss** [comment]
Right I don't have it in my models! I will add it with #62.

**Comment by ndureiss** [comment]
On your side @pchatard

**Comment by pchatard** [comment]
Works like a charm, closing!
