### ISSUE TITLE
[API] Edit List : Removing closureDate property

### ISSUE THREAD

**Issue by pchatard** [pchatard/giftlist#77]
When trying to edit a list, and removing an already set closureDate property, I get a 422 error.

I tried passing a null, an undefined or an empty string.

Could you please provide me a way of doing this ?

**Comment by ndureiss** [comment]
@pchatard ClosureDate can now be edited. To remove it, please use `null. For other optional fields, as strings, please pass an empty string.

**Comment by ndureiss** [comment]
Please close after checking the behavior.
